### ISSUE TITLE
ACL verification Carriage Return Error

### ISSUE THREAD

**Issue by AntCole** [fabric-composer/fabric-composer#192] opened 2017-02-16 12:19 UTC
From the ACL editor in Composer UI

if a carriage return is put between the rules, it throws a validation error under the editor

**Comment by dselman** [comment] 2017-02-18 13:35
The grammar currently splits on newlines -- so this is not a bug per se. We need a table-based editor for ACL rules, which may make this redundant, however I will keep this open until we come to consensus on the best way to edit ACL rules.

**Comment by dselman** [comment] 2017-03-08 09:15
Fixed in the new grammar for ACL.

**Closed by dselman** 2017-03-08 09:15 UTC
Labels: enhancement
