### ISSUE TITLE
As a Composer user, I shouldn't be able to define duplicate asset types

### ISSUE THREAD

**Issue by Jakeeyturner** [fabric-composer/fabric-composer#305] opened 2017-02-28 16:06 UTC
When creating a model file, it is possible to define an asset type multiple times without an error being thrown.

For example:

```
asset car identified by id {
  o String    id
  o String   color
}

asset car identified by id {
  o String    id
  o Integer  milesDriven
}
```

We shouldn't be able to let them deploy a model file with these asset definitions, as the first asset definition gets overwritten. Ideally we wouldn't let a user deploy this model file and should alert them of their mistake.

**Comment by dselman** [comment] 2017-02-28 22:08
Duplicate of #240

**Closed by dselman** 2017-02-28 22:08 UTC
Labels: bug
