### ISSUE TITLE
Can scroll down Playground page even though there is no content

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#418] opened 2017-03-10 08:43 UTC
## Context

The playground always has a scroll bar, indicating that there is something down the bottom of the page... but there is nothing there. 

## Expected Behavior

There should not be a scroll bar if there is no content.

## Actual Behavior

There is a scroll bar.

## Possible Fix

Figure out why the scroll bar is there.

## Steps to Reproduce

1. Open Playground
2. Scroll down page
3. See nothing new

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

Accidental scrolling made me need to scroll back up the page.

## Your Environment

* Version used: next-unstable
* Environment name and version (e.g. Chrome 39, node.js 5.4): Safari
* Operating System and version (desktop or mobile): MacOS
* Link to your project:

**Comment by sstone1** [comment] 2017-03-10 08:43
@winslet @samjsmith I think this probably related to the problem you were fixing yesterday, where the import button was in the footer?

**Comment by caroline-church** [comment] 2017-03-16 08:57
This is a duplicate of #442 so closing

**Closed by caroline-church** 2017-03-16 08:57 UTC
Labels: bug, P3, playground
