### ISSUE TITLE
Loopback connector does not support PUT operation

### ISSUE THREAD

**Issue by samjsmith** [fabric-composer/fabric-composer#315] opened 2017-03-01 11:56 UTC
You can 'Patch' assets at the moment but if you try PUT then you get this error message:
`The connector businessnetworkconnector does not support replaceById operation`

This really needs to be fixed

**Comment by sstone1** [comment] 2017-03-09 10:35
Duplicate of #402

**Closed by sstone1** 2017-03-09 10:35 UTC
Labels: bug
