### ISSUE TITLE
Useless error message when attempting to connect to hlfv1 without a valid connection profile

### ISSUE THREAD

**Issue by 14gracel** [fabric-composer/fabric-composer#662] opened 2017-04-11 13:22 UTC
Currently we see `TypeError: Cannot read property 'fail' of undefined
`
![image](https://cloud.githubusercontent.com/assets/17450713/24911178/fc23bfde-1ec1-11e7-9fd9-401abbde486b.png)

## Context
Takes much longer to debug why a network isn't deploying without a useful error message

## Expected Behavior
An error message saying something like `Invalid connection profile 'name' provided`

## Actual Behavior
Error message 'TypeError: Cannot read property 'fail' of undefined' given

## Steps to Reproduce
Try to connect to an instance of hlfv1 without providing a valid connection profile

## Context
Unable to debug why I could not deploy a business network

**Comment by 14gracel** [comment] 2017-04-11 13:58
@sstone1 @dselman Any suggestions about where this should be reported from? And where should we report that it is an issue with the connection profile? 
 I am no longer getting the `TypeError: Cannot read property 'fail' of undefined` message, but the message I'm now getting isn't much better 
```
Error: {"created":"@1491917377.429848146","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":2022,"grpc_status":14,"referenced_errors":[{"created":"@1491917377.429835576","description":"Expected SETTINGS frame as the first frame, got frame type 80","file":"../src/core/ext/transport/chttp2/transport/parsing.c","file_line":479}{"created":"@1491917377.429843158","description":"Trying to connect an http1.x server","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1995,"http_status":400}]}
```

**Comment by davidkel** [comment] 2017-04-12 15:15
I have seen this error for many reasons
1 - deploying a non-existant archive
2 - mistakes in connection.json files eg invalid paths to certificate files, path to keystore not valid, missing a quote out in connection.json itself
3 - connection profile doesn't exist

There seems to be a common theme for not locating files

**Comment by davidkel** [comment] 2017-04-18 11:06
@14gracel Hi Liam, mind if I take this as I know what the problem is and it has been a real issue for people over the last few days

**Comment by 14gracel** [comment] 2017-04-18 12:10
@davidkel Go for it

**Comment by davidkel** [comment] 2017-04-18 12:31
PR #699 merged

**Closed by davidkel** 2017-04-18 12:31 UTC
Labels: bug

**Comment by Cuica20** [comment] 2017-06-09 01:20
I have the following issue when execute the command: 
composer network deploy -a my-network.bna -p hlfv1 -i admin -s adminpw

Error: {"created":"@1496970882.724995000","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_tra
nsport.c","file_line":2022,"grpc_status":14,"referenced_errors":[{"created":"@1496970882.724982000","description":"Expected SETTINGS frame as
 the first frame, got frame type 80","file":"../src/core/ext/transport/chttp2/transport/parsing.c","file_line":479}{"created":"@1496970882.72
4989000","description":"Trying to connect an http1.x server","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_lin
e":1995,"http_status":400}]}

**Comment by vajadhav** [comment] 2017-07-26 07:03
I m facing the same issue , I wanted to know for CA peer,what is expected in "trustedRoots"  key ?
is that path for ca-cert.pem?
