### ISSUE TITLE
Playground doesn't really redeploy

### ISSUE THREAD

**Issue by samjsmith** [fabric-composer/fabric-composer#570] opened 2017-03-27 13:39 UTC
Load up playground with the Sample Business Network deployed.  Update it and then switch to the test tab and the network hasn't been updated

## Expected Behavior

It should update the in-memory business network

## Actual Behavior

It didn't update the in-memory business network

## Possible Fix

Nothing yet.

## Steps to Reproduce

1. Connect to playground in web browser
2. Delete contents of model file except for namespace
3. Click update
4. Switch to test tab and observe that asset/participant registries are still available

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

I was doing some testing 

## Your Environment

* Version used: 0.5.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome
* Operating System and version (desktop or mobile): Mac Sierrra
* Link to your project:

**Comment by samjsmith** [comment] 2017-03-27 13:42
In the case of an empty business network, the Playground UI should also really default to the Transactions view in the Testing panel with a different message indicating 'This is an empty business network'

I also observed the behaviour that the 'create...' button was there in the participant registry after I had removed the participant definition from the business network but this might be a side effect of the updated network not being deployed properly.  Just thought I'd mention it as an extra test case.

**Comment by samjsmith** [comment] 2017-03-27 16:18
Turns out that this seems to happen only when something is removed from a business network definition. I'm not sure what we expect to happen if you define an asset type, create some instances of that asset on the fabric, then remove that asset type.

**Comment by dselman** [comment] 2017-03-27 22:17
I think this is a dup of #489

**Comment by sstone1** [comment] 2017-03-27 22:21
Closing as dupe of #489, which isn't a bug either...

**Closed by sstone1** 2017-03-27 22:21 UTC
Labels: bug, P1, playground
